name: galactic_compass
description: Native compass for flutter. Tipti technical test
version: 1.0.0
homepage: "https://github.com/daniel-cch/galactic_compass"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.danielcch.galactic_compass
        pluginClass: GalacticCompassPlugin
      ios:
        pluginClass: GalacticCompassPlugin
